name: test `nix develop`

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  push:
    branches:
      - main

jobs:
  develop-x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix develop
                
  develop-aarch64-linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix develop
                
  develop-aarch64-darwin:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix develop
