name: test `nix-shell`

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  push:
    branches:
      - main

jobs:
  shell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix-shell
                
