name: QEMU esp32c3 test 

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          cd qemu-test && \
          nix-shell --run 'just switch-to-esp32c3 && just build && just run-with-timeout 10 | grep -q "loop: 2"'
                
